<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\Projekte\Kistl\Kistl.Tests\API.Tests\Kistl.APITests.nunit" total="1" failures="1" not-run="0" date="2008-04-14" time="14:32:39">
  <environment nunit-version="2.4.7.0" clr-version="2.0.50727.1433" os-version="Microsoft Windows NT 5.1.2600 Service Pack 2" platform="Win32NT" cwd="C:\Projekte\Kistl\Kistl.Tests\API.Tests" machine-name="MONEY" user="David" user-domain="MONEY" />
  <culture-info current-culture="de-AT" current-uiculture="de-DE" />
  <test-suite name="C:\Projekte\Kistl\Kistl.Tests\API.Tests\Kistl.APITests.nunit" success="False" time="1.719" asserts="0">
    <results>
      <test-suite name="C:\Projekte\Kistl\Kistl.Tests\API.Tests\bin\debug\..\Debug\API.Tests.dll" success="False" time="1.719" asserts="0">
        <results>
          <test-suite name="API" success="False" time="1.719" asserts="0">
            <results>
              <test-suite name="Tests" success="False" time="1.688" asserts="0">
                <results>
                  <test-suite name="Tests" success="False" time="0.219" asserts="0">
                    <results>
                      <test-suite name="LinqExtensionsTests" success="False" time="0.203" asserts="0">
                        <results>
                          <test-case name="API.Tests.Tests.LinqExtensionsTests.AddOrderBy" executed="True" success="False" time="0.172" asserts="0">
                            <failure>
                              <message><![CDATA[System.InvalidOperationException : Index was outside the bounds of the array.
NodeType: Lambda
Type: System.Func`2[API.Tests.TestDataObject,System.String]
GenericArgument[0][1]: ]]></message>
                              <stack-trace><![CDATA[at Kistl.API.LinqExtensions.AddOrderBy[T](IQueryable`1 queryable, Expression orderBy) in C:\Projekte\Kistl\Kistl.API\LinqExtensions.cs:line 66
at API.Tests.Tests.LinqExtensionsTests.AddOrderBy() in C:\Projekte\Kistl\Kistl.Tests\API.Tests\Tests\LinqExtensionsTests.cs:line 71
]]></stack-trace>
                            </failure>
                          </test-case>
                        </results>
                      </test-suite>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>